### ISSUE TITLE
twitter oauth実装、ユーザデータCRUD機能実装

### ISSUE THREAD

**Issue by tomoya128** [tomoya128/twitter_oauth_image_upload#1]
### twitter oauth実装

- [x] gem追加(twitter oauth)
- [x] callback時に、ユーザ情報登録
- [x] ユーザデータCRUD実装

### 参考URL

http://qiita.com/Hassan/items/176bc2c6fd75a3e00111

**Comment by tomoya128** [comment]
### users table

| Field         | Type         | Null | Key | Default | Extra          |
|---------------|--------------|------|-----|---------|----------------|
| id            | int(11)      | NO   | PRI | NULL    | auto_increment |
| nickname      | varchar(255) | YES  |     | NULL    |                |
| profile      | text | YES  |     | NULL    |                |
| image      | BLOB | YES  |     | NULL    |                |
| created_at    | datetime     | NO   |     | NULL    |                |
| updated_at    | datetime     | NO   |     | NULL    |                |

**Comment by kozakana** [comment]
imageは画像をS3に保存する想定(developmentはローカルファイルとして保存)でお願いします！
stringにしてpathを保存する感じで

**Comment by kozakana** [comment]
あ、あと画像保存にはcarrierwaveというgemを使ってもらえると助かります

**Comment by tomoya128** [comment]
@kozakana 

>imageは画像をS3に保存する想定(developmentはローカルファイルとして保存)でお願いします！
stringにしてpathを保存する感じで

>あ、あと画像保存にはcarrierwaveというgemを使ってもらえると助かります

ご教示ありがとうございます。
承知いたしました！！

**Comment by kozakana** [comment]
@tomoya128 
あと、providerとuidのユニーク制約も付けておいてください！

**Comment by tomoya128** [comment]
@kozakana 

承知いたしました。uniq indexを追加いたします。

**Comment by tomoya128** [comment]
こちらは、実装、レビュー、レビュー修正を
行いましたのでクローズします。
